// AUTH
export const AUTH_USER = "AUTH_USER"
export const LOGOUT = "LOGOUT"

// User
export const SUGGEST_INTEREST = "SUGGEST_INTEREST"
export const SET_USER_INTEREST = "SET_USER_INTEREST"
export const SET_USER_AVAILABILITY = "SET_USER_AVAILABILITY"

// Dashboard
export const UPDATE_DISPLAY_ROOMS = "UPDATE_DISPLAY_ROOMS"

// Room
export const UPDATE_USERS_IN_ROOM = "UPDATE_USERS_IN_ROOM"
export const SET_ROOM_STATUS = "SET_ROOM_STATUS"
export const SET_ROOM_INFORMATION = "SET_ROOM_INFORMATION"
